"""Permission model changed

Revision ID: da3e26eaa616
Revises: df88e4109863
Create Date: 2024-03-28 15:15:18.249239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da3e26eaa616'
down_revision = 'df88e4109863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('display_name', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['system_name'])
        batch_op.drop_column('name')

    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', postgresql.ENUM('CREATE', 'READ', 'UPDATE', 'DELETE', name='persmissionenum'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('display_name')
        batch_op.drop_column('system_name')

    # ### end Alembic commands ###
